### ISSUE TITLE
now i'm getting new error please help someone

### ISSUE THREAD

**Issue by pkmuz1** [jaseemkm/loco-hack#13]
Traceback (most recent call last):
  File "play.py", line 118, in <module>
    normal = normal_scores(question,options)
  File "play.py", line 33, in normal_scores
    results = google_search(question, api_key, cse_id, num=10)
  File "play.py", line 22, in google_search
    return res['items']
KeyError: 'items'

**Comment by Farhanshaikh6458** [comment]
https://www.youtube.com/watch?v=0oDEV-iojKE&feature=youtu.be here is the tutorial

**Comment by pkmuz1** [comment]
File "loco.py", line 100
    print scores
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(scores)?

what is this??? pls solve

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be
