### ISSUE TITLE
KeyError: 'textAnnotations'

### ISSUE THREAD

**Issue by manishchandwani** [jaseemkm/loco-hack#19]
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\loco-hack-master\play.py", line 114, in <module>
    options = [get_text_from_response(responses[1]),get_text_from_response(responses[2]),get_text_from_response(responses[3])]
  File "C:\Users\Dell\Desktop\loco-hack-master\play.py", line 74, in get_text_from_response
    t = response['textAnnotations'][0]
KeyError: 'textAnnotations'

**Comment by vvsvenkat** [comment]
Have you got the solution?

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be
