### ISSUE TITLE
jaseem bro help me to solve this issue

### ISSUE THREAD

**Issue by srinivasukotipalli** [jaseemkm/loco-hack#27]
RESTART: C:\Users\srini\Downloads\loco-hack-master\loco-hack-master\play.py 
Wait for the next question and press Enter key instantly when it's displayed

Traceback (most recent call last):
  File "C:\Users\srini\Downloads\loco-hack-master\loco-hack-master\play.py", line 105, in <module>
    split_screen_to_question_and_options()
  File "C:\Users\srini\Downloads\loco-hack-master\loco-hack-master\play.py", line 81, in split_screen_to_question_and_options
    i = Image.open('screen.png')
  File "C:\Users\srini\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'screen.png'

**Comment by manishchandwani** [comment]
have you connected your phone through adb.

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be
