### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by adad1223** [jaseemkm/loco-hack#29]
Traceback (most recent call last):
  File "C:\Users\anish\Desktop\Locohack.py", line 117, in <module>
    normal = normal_scores(question,options)
  File "C:\Users\anish\Desktop\Locohack.py", line 33, in normal_scores
    results = google_search(question, api_key, cse_id, num=10)
  File "C:\Users\anish\Desktop\Locohack.py", line 22, in google_search
    return res['items']
KeyError: 'items

**Comment by arpanjayeshkumarshukla** [comment]
Search had an error. See what is stored in res. Your free queries may have been exhausted.

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be
