### ISSUE TITLE
Key Error: Text annotations

### ISSUE THREAD

**Issue by vvsvenkat** [jaseemkm/loco-hack#31]
Traceback (most recent call last):
  File "C:\Users\Venkat\Desktop\Qureka\New folder\loco-hack.py", line 116, in <module>
    options = [get_text_from_response(responses[1]),get_text_from_response(responses[2]),get_text_from_response(responses[3])]
  File "C:\Users\Venkat\Desktop\Qureka\New folder\loco-hack.py", line 75, in get_text_from_response
    t = response['textAnnotations'][0]
KeyError: 'textAnnotations'

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be
