### ISSUE TITLE
raw_input

### ISSUE THREAD

**Issue by ramjitiwari1997** [jaseemkm/loco-hack#36]
API key returned by google is not matching by key 'itmes'
It shows as...
Traceback (most recent call last):
  File "play.py", line 118, in <module>
    normal = normal_scores(question,options)
  File "play.py", line 34, in normal_scores
    results = google_search(question, api_key, cse_id, num=10)
  File "play.py", line 23, in google_search
    return res['items']
KeyError: 'items'

**Comment by sensuraj** [comment]
@ramjitiwari1997 some times it happens with some questions because this bot has some defect all around.  Better If u want I can provide u the best bot of this generation "Trivex"
Mail me at sensuraj069@gmail.com
