### ISSUE TITLE
textAnnotations

### ISSUE THREAD

**Issue by silentsniperist** [jaseemkm/loco-hack#38]
pls help me someone to fix this error

Traceback (most recent call last):
  File "C:\Users\Sahil\Desktop\LOCO SCRIPT\LOCO HACK.py", line 114, in <module>
    question = get_text_from_response(responses[0])
  File "C:\Users\Sahil\Desktop\LOCO SCRIPT\LOCO HACK.py", line 75, in get_text_from_response
    t = response['textAnnotations'][0]
KeyError: 'textAnnotations'

**Comment by shashidharb96** [comment]
please fit your loco screen correctly so that all image are correctly aligned

**Comment by silentsniperist** [comment]
@shashidharb96 bro teach me how i am a beginner in this..the script gives some answer and some answer for not pls tell me how to do it pls.??
